name: Deploy Resume Infrastructure

on:
  push:
    branches: [ "main" ]
    paths: 
      - 'infra/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Subscription
      run: |
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      working-directory: ./infra
      run: terraform init

    - name: Terraform Plan  
      working-directory: ./infra
      run: terraform plan

    - name: Terraform Apply
      working-directory: ./infra
      run: terraform apply -auto-approve